name: issue_workflow
on: [workflow_dispatch, issues]
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: output GH issue
              run: |
                echo "Issue title: ${{ github.event.issue.title }}"
                echo "Issue title: ${{ github.event.issue.body }}"  