name: test workflow
on: push
jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v3
            - name: install nodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: install dependiencies
              run: npm ci
            - name: testing..
              run: |
                npm test
                npm build
